### ISSUE TITLE
publish on pypi

### ISSUE THREAD

**Issue by stefanfoulis** [translations-com/globallink-connect-api-python#1]
Make this package installable from https://pypi.python.org/pypi:

```
pip install globallink-connect
```

- [x] figure out dependencies (suds, ...)
- [x] create ``setup.py`` and ``MANIFEST.in`` (``.wsdl`` files!)
- [x] README describing basic usage

**Comment by stefanfoulis** [comment]
@nbezalwar is this something you'd be interested in? I can make a pull-request with the necessary changes.

**Comment by masanzsa** [comment]
@stefanfoulis we have plans to publish this in pypi, I will let you know once that is set

**Comment by masanzsa** [comment]
Hi @stefanfoulis 

You can find our package uploaded to pypi here:
https://pypi.python.org/pypi?:action=display&name=glexchange&version=4.18.0

Thanks!

Mariano
